// jenkins/Jenkinsfile/Different path
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Building from custom path Jenkinsfile"
            }
        }
    }
}
